apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quote-api
  template:
    metadata:
      labels:
        app: quote-api
    spec:
      containers:
      - name: quote-api
        image: <YOUR_IMAGE>
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: quote-api-service
spec:
  type: LoadBalancer
  selector:
    app: quote-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
